services:
  db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5050:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@user.com
  #     - PGADMIN_DEFAULT_PASSWORD=secret123
  #   depends_on:
  #     - db
