include:
  - ../postgres/docker-compose.yaml
  - ../rabbitmq/docker-compose.yaml
  - ../nginx/docker-compose.yaml

services:
  django:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:root@postgres:5432/django_videos
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ASSETS_URL=http://host.docker.internal:9000/media/uploads
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  external-storage:
    external: true
