include:
  - ../postgres/docker-compose.yaml
  - ../rabbitmq/docker-compose.yaml

services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 'true'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'converter'
      POSTGRES_HOST: 'postgres'
      POSTGRES_SSL_MODE: 'disable'
      RABBITMQ_URL: 'amqp://guest:guest@rabbitmq:5672/'
      CONVERSION_EXCHANGE: 'conversion_exchange'
      CONVERSION_KEY: 'conversion'
      CONVERSION_QUEUE: 'video_conversion_queue'
      CONFIRMATION_KEY: 'finish_conversion'
      CONFIRMATION_QUEUE: 'finish_conversion_queue'
      VIDEO_ROOT_PATH: '/media/uploads'
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

volumes:
  external-storage:
    external: true
