services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'converter'
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

volumes:
  external-storage:
    external: true
