services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 'true'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'converter'
      POSTGRES_HOST: 'postgres'
      POSTGRES_SSL_MODE: 'disable'
      RABBITMQ_URL: 'amqp://guest:guest@rabbitmq:5672/'
      CONVERSION_EXCHANGE: 'conversion_exchange'
      CONVERSION_KEY: 'conversion'
      CONVERSION_QUEUE: 'video_conversion_queue'
      CONFIRMATION_KEY: 'finish_conversion'
      CONFIRMATION_QUEUE: 'finish_conversion_queue'
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'converter'
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

volumes:
  external-storage:
    external: true
