services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'root'
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
      - ../go_transcoder/prepare-db.sql:/docker-entrypoint-initdb.d/prepare-db-golang.sql
      - ../django/prepare-db.sql:/docker-entrypoint-initdb.d/prepare-db-django.sql

  pgadmin:
    image: dpage/pgadmin4:2024-10-19-2
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
